name: Build Windows PDF Watcher

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create & activate venv, install deps
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Package with PyInstaller
        run: |
          .\venv\Scripts\activate
          pyinstaller --windowed --onedir --name PDFWatcher ^
            --hidden-import=jaraco.text ^
            --hidden-import=jaraco.context ^
            --hidden-import=jaraco.functools ^
            --hidden-import=autocommand ^
            pdfwatcherapp1.py

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-dist
          path: dist/PDFWatcher
